import path from 'path';
import {ChannelsPage, expect, test} from '@mattermost/playwright-lib';
const TEAM_ICON_ASSET = path.resolve(__dirname, '../../../../lib/src/asset/mattermost-icon_128x128.png');
test.describe('Team Settings Modal - Complete Test Suite', () => {
    test('MM-TXXXX Open and close Team Settings Modal', async ({pw}) => {
        const {adminUser} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto();
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        await expect(teamSettings.infoTab).toHaveAttribute('aria-selected', 'true');
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Edit team name and save changes', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        await expect(teamSettings.infoSettings.nameInput).toHaveValue(team.display_name);
        const newTeamName = `Updated Team ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateName(newTeamName);
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.display_name).toBe(newTeamName);
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Edit team description and save changes', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const newDescription = `Test description ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateDescription(newDescription);
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.description).toBe(newDescription);
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Warn on close with unsaved changes', async ({pw}) => {
        const {adminUser, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const newTeamName = `Modified Team ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateName(newTeamName);
        await teamSettings.close();
        await teamSettings.verifyUnsavedChanges();
        await expect(teamSettings.saveButton).toBeVisible();
        await expect(teamSettings.container).toBeVisible();
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Prevent tab switch with unsaved changes', async ({pw}) => {
        const {adminUser, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        await expect(teamSettings.accessTab).toBeVisible();
        const newTeamName = `Modified Team ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateName(newTeamName);
        await teamSettings.openAccessTab();
        await teamSettings.verifyUnsavedChanges();
        await expect(teamSettings.infoTab).toHaveAttribute('aria-selected', 'true');
        await teamSettings.undo();
        await teamSettings.openAccessTab();
        await expect(teamSettings.accessTab).toHaveAttribute('aria-selected', 'true');
    });
    test('MM-TXXXX Save changes and close modal without warning', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const newTeamName = `Updated Team ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateName(newTeamName);
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.display_name).toBe(newTeamName);
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Undo changes resets form state', async ({pw}) => {
        const {adminUser, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const newTeamName = `Modified Team ${await pw.random.id()}`;
        await teamSettings.infoSettings.updateName(newTeamName);
        await expect(teamSettings.infoSettings.nameInput).toHaveValue(newTeamName);
        await teamSettings.undo();
        await expect(teamSettings.infoSettings.nameInput).toHaveValue(team.display_name);
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
    });
    test('MM-TXXXX Upload and Remove team icon', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const infoSettings = teamSettings.infoSettings;
        await infoSettings.uploadIcon(TEAM_ICON_ASSET);
        await expect(infoSettings.teamIconImage).toBeVisible();
        await expect(infoSettings.removeImageButton).toBeVisible();
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const teamWithIcon = await adminClient.getTeam(team.id);
        expect(teamWithIcon.last_team_icon_update).toBeGreaterThan(0);
        await teamSettings.close();
        await expect(teamSettings.container).not.toBeVisible();
        const teamSettings2 = await channelsPage.openTeamSettings();
        await expect(teamSettings2.infoSettings.teamIconImage).toBeVisible();
        await expect(teamSettings2.infoSettings.removeImageButton).toBeVisible();
        await teamSettings2.infoSettings.removeIcon();
        await expect(teamSettings2.infoSettings.teamIconInitial).toBeVisible();
        const teamAfterRemove = await adminClient.getTeam(team.id);
        expect(teamAfterRemove.last_team_icon_update || 0).toBe(0);
        await teamSettings2.close();
    });
    test('MM-TXXXX Access tab - add and remove allowed domain', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const accessSettings = await teamSettings.openAccessTab();
        await expect(teamSettings.accessTab).toHaveAttribute('aria-selected', 'true');
        await accessSettings.enableAllowedDomains();
        const testDomain = 'testdomain.com';
        await accessSettings.addDomain(testDomain);
        const domainChip = teamSettings.container.locator('#allowedDomains').getByText(testDomain);
        await expect(domainChip).toBeVisible();
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.allowed_domains).toContain(testDomain);
        await accessSettings.removeDomain(testDomain);
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const finalTeam = await adminClient.getTeam(team.id);
        expect(finalTeam.allowed_domains).not.toContain(testDomain);
        await teamSettings.close();
    });
    test('MM-TXXXX Access tab - toggle allow open invite', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        const originalTeam = await adminClient.getTeam(team.id);
        const originalAllowOpenInvite = originalTeam.allow_open_invite ?? false;
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const accessSettings = await teamSettings.openAccessTab();
        await expect(teamSettings.accessTab).toHaveAttribute('aria-selected', 'true');
        await accessSettings.toggleOpenInvite();
        await expect(teamSettings.saveButton).toBeVisible();
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.allow_open_invite).toBe(!originalAllowOpenInvite);
        await accessSettings.toggleOpenInvite();
        await teamSettings.save();
        await teamSettings.verifySavedMessage();
        const finalTeam = await adminClient.getTeam(team.id);
        expect(finalTeam.allow_open_invite).toBe(originalAllowOpenInvite);
        await teamSettings.close();
    });
    test('MM-TXXXX Access tab - regenerate invite ID', async ({pw}) => {
        const {adminUser, adminClient, team} = await pw.initSetup();
        const {page} = await pw.testBrowser.login(adminUser);
        const channelsPage = new ChannelsPage(page);
        const originalInviteId = team.invite_id;
        await channelsPage.goto(team.name);
        await page.waitForLoadState('networkidle');
        const teamSettings = await channelsPage.openTeamSettings();
        const accessSettings = await teamSettings.openAccessTab();
        await expect(teamSettings.accessTab).toHaveAttribute('aria-selected', 'true');
        await accessSettings.regenerateInviteId();
        const updatedTeam = await adminClient.getTeam(team.id);
        expect(updatedTeam.invite_id).not.toBe(originalInviteId);
        expect(updatedTeam.invite_id).toBeTruthy();
        await teamSettings.close();
    });
});