import {expect, test} from '@mattermost/playwright-lib';
test('Search box suggestion must be case insensitive', async ({pw}) => {
    const {user} = await pw.initSetup();
    const {channelsPage} = await pw.testBrowser.login(user);
    await channelsPage.goto();
    await channelsPage.toBeVisible();
    await channelsPage.globalHeader.openSearch();
    const searchWord = 'off';
    const searchOutput = 'In:off-topic';
    const channelName = 'Off-Topic';
    const {searchInput} = channelsPage.searchBox;
    await searchInput.pressSequentially(`In:${searchWord}`);
    await expect(channelsPage.searchBox.selectedSuggestion).toBeVisible();
    await expect(channelsPage.searchBox.selectedSuggestion).toHaveText(channelName);
    await searchInput.press('Enter');
    await searchInput.press('Enter');
    await expect(channelsPage.globalHeader.searchBox.getByText(searchOutput, {exact: true})).toBeVisible();
    await channelsPage.globalHeader.openSearch();
    await channelsPage.searchBox.clearIfPossible();
    await searchInput.type(`In:${searchWord.toUpperCase()}`);
    await expect(channelsPage.searchBox.selectedSuggestion).toBeVisible();
    await expect(channelsPage.searchBox.selectedSuggestion).toHaveText(channelName);
    await searchInput.press('Enter');
    await searchInput.press('Enter');
    await expect(channelsPage.globalHeader.searchBox.getByText(searchOutput, {exact: true})).toBeVisible();
});
test('remove extra whitespace when selecting a user', async ({pw}) => {
    const {user, adminUser: admin} = await pw.initSetup();
    const {channelsPage} = await pw.testBrowser.login(user);
    await channelsPage.goto();
    await channelsPage.toBeVisible();
    await channelsPage.globalHeader.openSearch();
    const {searchInput} = channelsPage.searchBox;
    await searchInput.pressSequentially(`from:    ${admin.username}`);
    await expect(channelsPage.searchBox.selectedSuggestion).toBeVisible();
    await expect(channelsPage.searchBox.selectedSuggestion).toHaveText(`@` + admin.username);
    await searchInput.press('Enter');
    const expectedText = `from:${admin.username} `;
    await expect(searchInput).toHaveValue(expectedText);
});