import {test} from '@mattermost/playwright-lib';
test('Should be able to change threads with arrow keys', {tag: '@smoke'}, async ({pw}, testInfo) => {
    test.skip(testInfo.project.name === 'ipad');
    const {team, user} = await pw.initSetup();
    const {channelsPage, page, threadsPage} = await pw.testBrowser.login(user);
    await channelsPage.goto();
    await channelsPage.toBeVisible();
    await channelsPage.centerView.postCreate.postMessage('aaa');
    await (await channelsPage.getLastPost()).openAThread();
    await channelsPage.sidebarRight.postMessage('aaa reply');
    await channelsPage.centerView.postCreate.postMessage('bbb');
    await (await channelsPage.getLastPost()).openAThread();
    await channelsPage.sidebarRight.postMessage('bbb reply');
    await channelsPage.sidebarRight.postCreate.writeMessage('bbb second reply');
    await channelsPage.centerView.postCreate.postMessage('ccc');
    await (await channelsPage.getLastPost()).openAThread();
    await channelsPage.sidebarRight.postMessage('ccc reply');
    await channelsPage.sidebarLeft.draftsVisible();
    await threadsPage.goto(team.name);
    await threadsPage.toBeVisible();
    await threadsPage.toNotHaveThreadSelected();
    await page.keyboard.press('ArrowDown');
    await threadsPage.toHaveThreadSelected();
    await (await threadsPage.getLastPost()).toContainText('ccc reply');
    await page.keyboard.press('ArrowDown');
    await threadsPage.toHaveThreadSelected();
    await (await threadsPage.getLastPost()).toContainText('bbb reply');
    await threadsPage.threadsList.focus();
    await page.keyboard.press('ArrowDown');
    await threadsPage.toHaveThreadSelected();
    await (await threadsPage.getLastPost()).toContainText('aaa reply');
    await page.keyboard.press('ArrowUp');
    await threadsPage.toHaveThreadSelected();
    await (await threadsPage.getLastPost()).toContainText('bbb reply');
    await page.keyboard.press('ArrowUp');
    await threadsPage.toHaveThreadSelected();
    await (await threadsPage.getLastPost()).toContainText('ccc reply');
});