import {expect, test} from '@mattermost/playwright-lib';
import {createPost, verifyAuthorNotification, setupContentFlagging} from './../support';
test.skip('should not be able to restore flagged messages when author deletes message', async ({pw}) => {
    const {adminClient, team, user: reviewerUser} = await pw.initSetup();
    const reporterUser = await pw.random.user('second');
    const {id: reporterUserID} = await adminClient.createUser(reporterUser, '', '');
    await adminClient.addToTeam(team.id, reporterUserID);
    const postFromThirdUser = await pw.random.user('third');
    const {id: postFromThirdUserID} = await adminClient.createUser(postFromThirdUser, '', '');
    await adminClient.addToTeam(team.id, postFromThirdUserID);
    const {client: thirdUserClient} = await pw.makeClient(postFromThirdUser);
    const {client: reporterUserClient} = await pw.makeClient(reporterUser);
    await setupContentFlagging(adminClient, [reviewerUser.id], true, false);
    const message = `Post by @${reviewerUser.username}, is flagged once`;
    const {post} = await createPost(adminClient, thirdUserClient, team, postFromThirdUser, message);
    await reporterUserClient.flagPost(post.id, 'Classification mismatch', 'This message is inappropriate');
    await thirdUserClient.deletePost(post.id);
    const flagReport = await adminClient.getFlaggedPost(post.id);
    expect(flagReport.delete_at).not.toBe(0);
    const {channelsPage, contentReviewPage} = await pw.testBrowser.login(reviewerUser);
    await channelsPage.goto(team.name, 'town-square');
    await channelsPage.toBeVisible();
    await verifyAuthorNotification(post.id, channelsPage, contentReviewPage, team.name, message, 'Removed');
});